name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install pytest (you can use some other testing utility)
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Run the tests. I'm using pytest and the file is in the tests directory.
      - name: Run tests        
        run: export PYTHONPATH=.; pytest¨
      - uses: actions/checkout@master
        #Run code coverage
      - name: Upload coverage reports to Codecov with GitHub Action
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)  